### PR TITLE
Correct commands and links to use buildpacks-community repository

### PR DESCRIPTION
**Pull request by gogolok**

### CODE REVIEW

**Comment by gogolok** [comment]
I haven't touched the file `kp.rb` yet. This should probably be a separate commit/PR.

**Review by jjbustamante — APPROVED** [review]
LGTM

Thanks @gogolok

**Comment by jjbustamante** [comment]
Do we need to update first `kp.rb`  before merging this one?

**Comment by gogolok** [comment]
The download urls within `kp.rb` are still valid. This can be changed independently.

Also it looks to me like the `Build Service CI` is creating those urls (see https://github.com/buildpacks-community/homebrew-kpack-cli/commit/ae0d6d6f18c13bd804903835f31662ba65892cd2 ). So this needs to be fixed first I guess.
https://github.com/buildpacks-community/kpack-cli/blob/main/.github/workflows/homebrew.yaml suggests this should not happen. So not sure what's happening regarding this.

But this PR will work independent of what `kp.rb` specifies.

**Comment by jjbustamante** [comment]
@tomkennedy513  can you take a look at this?

**Review by tomkennedy513 — APPROVED** [review]

**Pull request merged**
